import pyface.qt
import processDAE
from mayavi.mlab import *
from xml.etree import ElementTree as ET




#plots triangular mesh using clusters as scalar for shading
#inputs: path to xml collada file, clusters array generated by kmeans
#outputs: shaded 3d model
def plt(vertices, triangleMap, clusters):
    x = [vertices[i][0] for i in range(0, len(vertices))]
    y = [vertices[i][1] for i in range(0, len(vertices))]
    z = [vertices[i][2] for i in range(0, len(vertices))]

    mesh = triangular_mesh(x, y, z, triangleMap,representation='wireframe',opacity=0)
    mesh.mlab_source.dataset.cell_data.scalars = clusters
    mesh.mlab_source.dataset.cell_data.scalars.name = 'Clusters'
    mesh.mlab_source.update()
    mesh.parent.update()

    mesh2 = pipeline.set_active_attribute(mesh, cell_scalars='Clusters')
    pipeline.surface(mesh2)
    show()
